### ISSUE TITLE
Module and function descriptions

### ISSUE THREAD

**Issue by azeemshatp** [LibreSolar/charge-controller-firmware#57]
Can we have a module description at the beginning of each file. Also, function descriptions before each function definition. 
Example: in files bat_charger.cpp, dcdc.cpp

**Comment by martinjaeger** [comment]
The function descriptions are already in the header files. Or did you miss anything there?

See also the auto-generated documentation: https://libre.solar/charge-controller-firmware/

I agree that the description of what each file does (also at the beginning of the header file) is quite short in most cases. Could certainly be improved.

**Comment by martinjaeger** [comment]
Closing this issue as description is present in header files and Doxygen documentation.
