### ISSUE TITLE
Implement global debug print function

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/charge-controller-firmware#58]
It would make sense to have a possibility to switch on / off all serial output debug messages at once. I will research if there is such a method in mbed. Otherwise we can define our own macro `DEBUG_PRINT` (or is there something more suitable from C++ world, @hogthrob ?) in the main.h file.

**Comment by hogthrob** [comment]
Sounds good. Would do the job. Probably a C++ crack would have some ideas how to do this without the preprocessor, but your proposal will do the job just fine.

**Comment by JordanSilverman** [comment]
This approach sounds good. I would suggest we implement a 4th function `print_comms` in order to set the comms debug messages separately.
