### ISSUE TITLE
Load not switching on with 24V system

### ISSUE THREAD

**Issue by Dee-Fuse** [LibreSolar/charge-controller-firmware#96]
I've found another bug regarding the series multiplier in 24V systems.
The Load wont switch on due to a overvoltage condition in [load.cpp:L72](https://github.com/LibreSolar/charge-controller-firmware/blob/882f2813332a326d2cebf0f6ac6f8f0cc0b3f8a6/src/load.cpp#L72)
```
        if (bus->voltage [25.4] > overvoltage [14.7] || bus->voltage [25.4] >
            DT_CHARGE_CONTROLLER_PCB_LS_VOLTAGE_MAX [32])
```
The variable `overvoltage` is beeing set by 
```
load.set_voltage_limits(bat_conf.voltage_load_disconnect [11.7], bat_conf.voltage_load_reconnect [12.6],
        bat_conf.voltage_absolute_max [14.7]);
```
 in [main.cpp:L65](https://github.com/LibreSolar/charge-controller-firmware/blob/882f2813332a326d2cebf0f6ac6f8f0cc0b3f8a6/src/main.cpp#L65l)

These values shoud be adjusted with the series multiplier to account for 24V systems.

**Comment by martinjaeger** [comment]
Thanks for the bug report. It should be fixed with above mentioned commit.
